create table STUDENT(
SID NUMBER(10) not null,
SNAME VARCHAR2(30), 
ADDRESS VARCHAR2(30),
CITY VARCHAR2(30), 
STATE VARCHAR2(30)
ZIPCODE NUMBER(5), 
TELEPHONE NUMBER(11), 
EMAIL VARCHAR2(30),
URL VARCHAR2(50), 
DOS DATE, 
PRIMARY KEY (SID) );


